insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,  1, 1,0,'apa','what');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,  2, 1,0,'siapa','who');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,  3, 1,0,'ke mana','where to');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,  4, 1,0,'di mana','where');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,  5, 1,0,'kapan','when');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,  6, 1,0,'mengapa','why');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,  7, 1,0,'bagaimana','how');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,  8, 1,0,'berapa','how much, how many');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,  9, 1,0,'ini','this');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 10, 1,0,'itu','that');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 11, 1,0,'lagi','else');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 12, 1,0,'hari','day');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 13, 1,0,'besok','tomorrow');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 14, 1,0,'yang','which');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 15, 1,0,'anda','you');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 16, 1,0,'cari','look');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 17, 1,0,'perkulan','need');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 18, 1,0,'datang','come');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 19, 1,0,'tas','bag');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 20, 1,0,'menelepon','calling');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 21, 1,0,'ikut','come along');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 22, 1,0,'dengan','with');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 23, 1,0,'pergi','go');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 24, 1,0,'tujuan','destination');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 25, 1,0,'tujuannya','destination');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 26, 1,0,'sekarang','now');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 27, 1,0,'berlibur','vacation');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 28, 1,0,'bus','bus');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 29, 1,0,'dibawa','taken, brought');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 30, 1,0,'tinggal','stay');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 31, 1,0,'teman','friend');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 32, 1,0,'lahir','born');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 33, 1,0,'tempatnya','place');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 34, 1,0,'pasport','passport');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 35, 1,0,'saya','I, me, my, mine');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 36, 1,0,'dokter','doctor');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 37, 1,0,'terdekat','nearest');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 38, 1,0,'akan','will');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 39, 1,0,'selesai','finished');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 40, 1,0,'pesta','party');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 41, 1,0,'dimulai','begin');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 42, 1,0,'dibangun','build, construct');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 43, 1,0,'kita','we');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 44, 1,0,'ke','from');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 45, 1,0,'duduk','sit');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 46, 1,0,'mereka','they');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 47, 1,0,'tertawa','laugh');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 48, 1,0,'hendak','want');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 49, 1,0,'harganya','price');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 50, 1,0,'mahal','expensive');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 51, 1,0,'terlambat','late');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 52, 1,0,'gembira','happy');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 53, 1,0,'keadaannya','situation');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 54, 1,0,'rasa','taste');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 55, 1,0,'rasanya','taste');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 56, 1,0,'caranya','how');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 57, 1,0,'cuaca','weather');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 58, 1,0,'di','in');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 59, 1,0,'wajah','face');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 60, 1,0,'harganya','price');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 61, 1,0,'anak','children');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 62, 1,0,'biayanya','cost');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 63, 1,0,'sana','there');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 64, 1,0,'beratnya','weight');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 65, 1,0,'jaraknya','distance');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 66, 1,0,'lama','long');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 67, 1,0,'sini','here');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 68, 1,0,'km','km');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 69, 1,0,'kg','kg');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 70, 1,0,'durian','durian, a fruit');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 71, 1,0,'Bandung','a place');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 72, 1,0,'Jakarta','the capital city of Indonesia');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 73, 1,0,'Borobudur','a landmark in Indonesia');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 74, 1,0,'apa','what');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 75, 1,0,'Apa ini?','What is this?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 76, 1,0,'Apa itu?','What is that?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 77, 1,0,'Apa lagi?','What else?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 78, 1,0,'Hari apa besok?','Day what tomorrow?  What day is tomorrow?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 79, 1,0,'Apa yang anda cari?','What which you look for?  What are you looking for?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 80, 1,0,'Apa yang anda perlukan?','What which you need?  What do you need?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 81, 1,0,'siapa','who');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 82, 1,0,'Siapa anda?','Who are you?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 83, 1,0,'Siapa yang datang?','Who is coming?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 84, 1,0,'Tas siapa ini?','Whose bag is this?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 85, 1,0,'Siapa yang menelepon?','Who which calling?  Who is calling?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 86, 1,0,'Siapa yang ikut?','Who which come along?  Who will come along?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 87, 1,0,'Dengan siapa anda pergi?','With whom you go?  Whom are you going with?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 88, 1,0,'ke mana','where to');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 89, 1,0,'Ke mana anda pergi?','Where are you going?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 90, 1,0,'Ke mana tujuannya?','Where is the destination?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 91, 1,0,'Ke mana lagi sekarang?','Where else now?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 92, 1,0,'Ke mana anda berlibur?','Where you vacation?  Where will you go on vacation?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 93, 1,0,'Ke mana tujuan bus ini?','Where go to bus this?  Where does this bus go?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 94, 1,0,'ke mana tas itu dibawa?','Where bag that brought?  Where will that bag be brought?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 95, 1,0,'di mana','where');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 96, 1,0,'Di mana anda tinggal?','Where do you stay?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 97, 1,0,'Di mana teman anda?','Where is your friend?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 98, 1,0,'Di mana anda lahir?','Where were you born?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4, 99, 1,0,'Di mana tempatnya?','Where the place?  Where is the place?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,100, 1,0,'Di mana pasport saya?','Where passport my?  Where is my passport?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,101, 1,0,'Di mana dokter terdekat?','Where is the nearest doctor?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,102, 1,0,'kapan','when');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,103, 1,0,'Kapan anda datang?','When did you come?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,104, 1,0,'Kapan anda pergi?','When will you go?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,105, 1,0,'Kapan itu akan selesai?','When will it be finished?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,106, 1,0,'Kapan pesta dimulai?','When party begin?  When will the party begin?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,107, 1,0,'Kapan Borobudur dibangun?','When Borobudur constructed?  When was the Borobudur built?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,108, 1,0,'Kapan kita ke Jakarta?','When we to Jakarta?  When will we go to Jakarta?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,109, 1,0,'mengapa','why');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,110, 1,0,'Mengapa anda duduk?','Why are you sitting?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,111, 1,0,'Mengapa mereka tertawa?','Why are they laughing?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,112, 1,0,'Mengapa anda hendak pergi?','Why are you leaving?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,113, 1,0,'Mengapa harganya mahal?','Why the price expensive?  Why is the price expensive?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,114, 1,0,'Mengapa anda terlambat?','Why you late?  Why are you late?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,115, 1,0,'Mengapa anda gembira?','Why you happy?  Why are you happy?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,116, 1,0,'bagaimana','how');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,117, 1,0,'Bagaimana keadaannya?','How is it?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,118, 1,0,'Bagaimana rasanya?','How does it taste?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,119, 1,0,'Bagaimana caranya?','How is it done?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,120, 1,0,'Bagaimana cuaca di Bandung?','How weather in Bandung?  How is the weather in Bandung?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,121, 1,0,'Bagaimana rasa durian?','How taste durian?  How does durian taste?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,122, 1,0,'Bagaimana wajah saya?','How face my?  How do I look?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,123, 1,0,'berapa','how much, how many');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,124, 1,0,'Berapa harganya?','How much does it cost?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,125, 1,0,'Berapa anak anda?','How many children do you have?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,126, 1,0,'Berapa biayanya ke sana?','How much does it cost to go there?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,127, 1,0,'Berapa kg beratnya?','How many kg the weigh?  How many kgs does it weigh?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,128, 1,0,'Berapa km jaraknya?','How many km distance?  How many kms is the distance?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(4,129, 1,0,'Berapa lama anda di sini?','How long you here?  How long will you stay here?');
