insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3,  1, 1,0,'apa','what');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3,  2, 1,0,'Apa ini?','What is this?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3,  3, 1,0,'Apa itu?','What is that?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3,  4, 1,0,'Apa lagi?','What else?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3,  5, 1,0,'Hari apa besok?','Day what tomorrow?  What day is tomorrow?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3,  6, 1,0,'Apa yang anda cari?','What which you look for?  What are you looking for?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3,  7, 1,0,'Apa yang anda perlukan?','What which you need?  What do you need?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3,  8, 1,0,'siapa','who');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3,  9, 1,0,'Siapa anda?','Who are you?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 10, 1,0,'Siapa yang datang?','Who is coming?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 11, 1,0,'Tas siapa ini?','Whose bag is this?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 12, 1,0,'Siapa yang menelepon?','Who which calling?  Who is calling?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 13, 1,0,'Siapa yang ikut?','Who which come along?  Who will come along?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 14, 1,0,'Dengan siapa anda pergi?','With whom you go?  Whom are you going with?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 15, 1,0,'ke mana','where to');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 16, 1,0,'Ke mana anda pergi?','Where are you going?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 17, 1,0,'Ke mana tujuannya?','Where is the destination?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 18, 1,0,'Ke mana lagi sekarang?','Where else now?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 19, 1,0,'Ke mana anda berlibur?','Where you vacation?  Where will you go on vacation?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 20, 1,0,'Ke mana tujuan bus ini?','Where go to bus this?  Where does this bus go?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 21, 1,0,'ke mana tas itu dibawa?','Where bag that brought?  Where will that bag be brought?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 22, 1,0,'di mana','where');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 23, 1,0,'Di mana anda tinggal?','Where do you stay?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 24, 1,0,'Di mana teman anda?','Where is your friend?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 25, 1,0,'Di mana anda lahir?','Where were you born?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 26, 1,0,'Di mana tempatnya?','Where the place?  Where is the place?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 27, 1,0,'Di mana pasport saya?','Where passport my?  Where is my passport?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 28, 1,0,'Di mana dokter terdekat?','Where is the nearest doctor?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 29, 1,0,'kapan','when');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 30, 1,0,'Kapan anda datang?','When did you come?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 31, 1,0,'Kapan anda pergi?','When will you go?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 32, 1,0,'Kapan itu akan selesai?','When will it be finished?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 33, 1,0,'Kapan pesta dimulai?','When party begin?  When will the party begin?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 34, 1,0,'Kapan Borobudur dibangun?','When Borobudur constructed?  When was the Borobudur built?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 35, 1,0,'Kapan kita ke Jakarta?','When we to Jakarta?  When will we go to Jakarta?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 36, 1,0,'mengapa','why');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 37, 1,0,'Mengapa anda duduk?','Why are you sitting?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 38, 1,0,'Mengapa mereka tertawa?','Why are they laughing?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 39, 1,0,'Mengapa anda hendak pergi?','Why are you leaving?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 40, 1,0,'Mengapa harganya mahal?','Why the price expensive?  Why is the price expensive?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 41, 1,0,'Mengapa anda terlambat?','Why you late?  Why are you late?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 42, 1,0,'Mengapa anda gembira?','Why you happy?  Why are you happy?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 43, 1,0,'bagaimana','how');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 44, 1,0,'Bagaimana keadaannya?','How is it?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 45, 1,0,'Bagaimana rasanya?','How does it taste?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 46, 1,0,'Bagaimana caranya?','How is it done?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 47, 1,0,'Bagaimana cuaca di Bandung?','How weather in Bandung?  How is the weather in Bandung?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 48, 1,0,'Bagaimana rasa durian?','How taste durian?  How does durian taste?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 49, 1,0,'Bagaimana wajah saya?','How face my?  How do I look?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 50, 1,0,'berapa','how much, how many');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 51, 1,0,'Berapa harganya?','How much does it cost?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 52, 1,0,'Berapa anak anda?','How many children do you have?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 53, 1,0,'Berapa biayanya ke sana?','How much does it cost to go there?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 54, 1,0,'Berapa kg beratnya?','How many kg the weigh?  How many kgs does it weigh?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 55, 1,0,'Berapa km jaraknya?','How many km distance?  How many kms is the distance?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(3, 56, 1,0,'Berapa lama anda di sini?','How long you here?  How long will you stay here?');
