insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8,  1, 1,0,'suka', 'like');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8,  2, 1,0,'mau','to want');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8,  3, 1,0,'perlu','to need');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8,  4, 1,0,'baca','to read');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8,  5, 1,0,'menulis','to write');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8,  6, 1,0,'mandi','to bathe');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8,  7, 1,0,'jual','to sell');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8,  8, 1,0,'lihat','to see, to look at');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8,  9, 1,0,'duduk','to sit');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 10, 1,0,'berdiri','to stand');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 11, 1,0,'tinggal','to live, to stay');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 12, 1,0,'datang','to come');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 13, 1,0,'jalan','to walk');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 14, 1,0,'berjalan','to walk');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 15, 1,0,'menjalan','to run');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 16, 1,0,'pergi','to go');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 17, 1,0,'kembali','to return');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 18, 1,0,'menunggu','to wait');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 19, 1,0,'berhenti','to stop');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 20, 1,0,'beristirahat','to rest');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 21, 1,0,'menyopir','to drive');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 22, 1,0,'tahu','to know');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 23, 1,0,'ingat','to remember');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 24, 1,0,'lupa','to forget');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 25, 1,0,'makan','to eat');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 26, 1,0,'minum','to drink');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 27, 1,0,'masuk','to come in');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 28, 1,0,'mulai','to start, begin');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 29, 1,0,'punya','to have');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 30, 1,0,'berbicara','to speak');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 31, 1,0,'tidur','to sleep');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 32, 1,0,'bangun','to wake up');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 33, 1,0,'belajar','to study');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 34, 1,0,'bekerja','to work');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 35, 1,0,'bermain','to play');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 36, 1,0,'mengunci','to lock');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 37, 1,0,'sedang','currently');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 38, 1,0,'akan','will');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 39, 1,0,'sudah','already');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 40, 1,0,'belum','not yet');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 41, 1,0,'pernak','ever');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 42, 1,0,'marih','still');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 43, 1,0,'ingin','want');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 44, 1,0,'harus','must');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 45, 1,0,'perlu','necessary, need');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 46, 1,0,'saka','like');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 47, 1,0,'boleh','may');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 48, 1,0,'dapat','can');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 49, 1,0,'mungkin','maybe');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 50, 1,0,'sangat','very');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 51, 1,0,'agak','so-so');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(8, 52, 1,0,'cukup','enough');
