insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9,  1, 1,0,'bercermin','to reflect, to mirror');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9,  2, 1,0,'dengar','to hear');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9,  3, 1,0,'gendong','to carry');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9,  4, 1,0,'keluar','to go out');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9,  5, 1,0,'pulang','to go home');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9,  6, 1,0,'jatuh','to fall');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9,  7, 1,0,'berangat','to leave');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9,  8, 1,0,'berati','to mean');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9,  9, 1,0,'berbelanja','to shop');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 10, 1,0,'bercerita','to tell (a story)');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 11, 1,0,'berdoa','to pray');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 12, 1,0,'berhasil','to succeed');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 13, 1,0,'berkata','to say, to tell');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 14, 1,0,'berlari','to run');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 15, 1,0,'berpikir','to think');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 16, 1,0,'berenang','to swim');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 17, 1,0,'bersembunyi','to hide');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 18, 1,0,'bertanya','to ask');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 19, 1,0,'bertemu','to meet');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 20, 1,0,'membawa','to bring, carry');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 21, 1,0,'membuka','to open');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 22, 1,0,'membeli','to buy');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 23, 1,0,'memakai','to wear, use');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 24, 1,0,'memotong','to cut');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 25, 1,0,'meminjam','to borrow');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 26, 1,0,'melihat','to see, to lookat');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 27, 1,0,'melompat','to jump');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 28, 1,0,'memasak','to cook');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 29, 1,0,'meminta','to ask for something');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 30, 1,0,'menikah','to marry');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 31, 1,0,'menyanyi','to sing');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 32, 1,0,'merusak','to break');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 33, 1,0,'merasa','to feel');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 34, 1,0,'mencuci','to wash');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 35, 1,0,'mencoba','to try');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 36, 1,0,'mendorong','to push');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 37, 1,0,'mendengar','to hear');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 38, 1,0,'menjadi','to become');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 39, 1,0,'menjawab','to answer');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 40, 1,0,'mengambil','to take');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 41, 1,0,'mengimpor','to import');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 42, 1,0,'menggoreng','to fry');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 43, 1,0,'mengganggu','to disturb');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 44, 1,0,'mengharap','to hope');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 45, 1,0,'menghitun','to count');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 46, 1,0,'mengetik','to type');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 47, 1,0,'menyimpan','to keep');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 48, 1,0,'menyuruh','to command');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 49, 1,0,'mengecat','to paint');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 50, 1,0,'mengebom','to bomb');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 51, 1,0,'mengecek','to check');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(9, 52, 1,0,'mengepel','to mop');
