insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,  1, 1,0,'Halo','Hi');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,  2, 1,0,'Selamat pagi','Good morning');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,  3, 1,0,'Selamat siang','Good afternoon');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,  4, 1,0,'Selamat sore','Good evening');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,  5, 1,0,'Selamat datang','Welcome');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,  6, 1,0,'Halo temanku','Hello my friend');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,  7, 1,0,'Apa kabar?','How are you?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,  8, 1,0,'Baik-baik saja, terima kasih.','I''m fine, thank you.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,  9, 1,0,'Bagaimana dengan Anda?','And you?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 10, 1,0,'Baik.','Good');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 11, 1,0,'Tidak begitu baik.','Not so good.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 12, 1,0,'Lama tidak berjumpa.','Long time no see.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 13, 1,0,'Kangen.','I missed you.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 14, 1,0,'Aka kabar baru?','What''s new?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 15, 1,0,'Tidak ada yang baru.','Nothing new.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 16, 1,0,'Terima kasih banyak.','Thank you very much.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 17, 1,0,'Kembali.','You''re welcome.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 18, 1,0,'Dengan senang hati.','My pleasure.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 19, 1,0,'Mari.','Come in.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 20, 1,0,'Santailah serasa di rumah Anda.','Make yourself at home.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 21, 1,0,'Semoga hari Anda menyenangkan.','Have a nice day.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 22, 1,0,'Salam malam.','Good night.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 23, 1,0,'Mimpi yang indah.','Good night and sweet dreams.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 24, 1,0,'Sampai nanti.','See you later.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 25, 1,0,'Sampai besok.','See you tomorrow.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 26, 1,0,'Sampai jumpa.','Good bye.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 27, 1,0,'Semoga perjalanan Anda menyenangkan.','Have a good trip.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 28, 1,0,'Saya harus pergi.','I have to go.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 29, 1,0,'Saya segera kembali.','I will be right back.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 30, 1,0,'Semoga beruntung.','Good luck.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 31, 1,0,'Selamat ulang tahun.','Happy birthday.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 32, 1,0,'Selamat tahun baru.','Happy new year.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 33, 1,0,'Selamat natal.','Merry Christmas.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 34, 1,0,'Selamat Hari Paskah.','Happy Easter');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 35, 1,0,'Selamat.','Congratulations.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 36, 1,0,'Selamat menikmati.','Enjoy.  Bon appetit.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 37, 1,0,'Terimalah ucapan saya.','Accept my best wishes.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 38, 1,0,'Siapa nama Anda?','What''s your name?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 39, 1,0,'Nama saya adalah John.','My name is John.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 40, 1,0,'Senang bertemu dengan Anda.','Nice to meet you.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 41, 1,0,'Dari mana asal Anda?','Where are you from?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 42, 1,0,'Saya dari Amerika.','I''m from America.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 43, 1,0,'Saya orang Amerika.','I am American.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 44, 1,0,'Anda tinggal di mana?','Where do you live?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 45, 1,0,'Saya tinggal di Ubud.','I live in Ubud.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 46, 1,0,'Apakah Anda suka di sini?','Do you like it here?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 47, 1,0,'Indonesia adalah negara yang indah.','Indonesia is a beautiful country.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 48, 1,0,'Apakah pekerjaan Anda?','What do you do for a living?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 49, 1,0,'Saya guru.','I''m a teacher.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 50, 1,0,'Saya pelajar.','I''m a student.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 51, 1,0,'Saya insinyur.','I''m an engineer.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 52, 1,0,'Apakah anda bisa berbahasa Indonesia?','Do you speak Indonesian?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 53, 1,0,'Sedikit saja.','Just a little.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 54, 1,0,'Saya suka bahasa Indonesia.','I like Indonesian.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 55, 1,0,'Saya sedang berusaha belajar bahasa Indonesia.','I''m trying to learn Indonesian.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 56, 1,0,'Sebuah bahasa yang sulit.','It''s a hard language.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 57, 1,0,'Sebuah bahasa yang mudah.','It''s an easy language.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 58, 1,0,'Oh.  Itu bagus.','Oh.  That''s good.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 59, 1,0,'Bolehkah saya berlatih dengan Anda?','Can I practice with you?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 60, 1,0,'Saya akan berusaha belajar sebisa saya.','I will try my best to learn.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 61, 1,0,'Umur berapakah Anda?','How old are you?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 62, 1,0,'Saya dua puluh satu tahun.','I''m twenty-one years old.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 63, 1,0,'Senang berbicara dengan Anda.','It was nice talking to you.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 64, 1,0,'Senang bertemu dengan Anda.','It was nice meeting you.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 65, 1,0,'Bapak','Mr.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 66, 1,0,'Ibu','Mrs.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 67, 1,0,'Nona','Miss');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 68, 1,0,'Ini istri saya.','This is my wife');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 69, 1,0,'Ini suami saya.','This is my husband.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 70, 1,0,'Sampaikan salam saya untuk Thomas.','Say hi to Thomas for me.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 71, 1,0,'Apakah Anda ada waktu kosong besok sore?','Are you free tomorrow evening?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 72, 1,0,'Saya ingin mengundang anda makan malam.','I would like to invite you to dinner.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 73, 1,0,'Anda terlihat cantik.','You look beautiful.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 74, 1,0,'Anda mempunyai nama yang indah.','You have a beautiful name.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 75, 1,0,'Bisakah Anda bercerita lebih banyak tentang anda?','Can you tell me more about you?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 76, 1,0,'Anda sudah menikah?','Are you married?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 77, 1,0,'Saya singel.','I''m single.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 78, 1,0,'Saya sudah menikah.','I''m married.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 79, 1,0,'Bolehkah saya minta nomor telepon Anda?','Can I have your phone number?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 80, 1,0,'Bolehkah saya minta alamat email Anda?','can I have your email?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 81, 1,0,'Apakah Anda mempunyai foto?','Do you have any pictures of you?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 82, 1,0,'Apakah Anda mempunyai anak?','Do you have children?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 83, 1,0,'Apakah Anda mau jalan-jalan?','Would you like to go for a walk?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 84, 1,0,'Aku suka kamu.','I like you.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 85, 1,0,'Aku cinta kamu.','I love you.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 86, 1,0,'Anda sungguh spesial.','You''re very special.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 87, 1,0,'Anda sangat baik.','You''re very kind.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 88, 1,0,'Saya sangat bahagia.','I''m very happy.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 89, 1,0,'Maukah kamu menikah denganku?','Would you marry me?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 90, 1,0,'Saya hanya bercanda.','I''m just kidding.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 91, 1,0,'Saya serius.','I''m serious.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 92, 1,0,'Hatiku berbicara bahasa cinta.','My heart speaks the language of love.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 93, 1,0,'Permisi.','I beg your pardon.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 94, 1,0,'Maaf.','Sorry.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 95, 1,0,'Tidak masalah.','No problem.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 96, 1,0,'Bisa tolong ulangi?','Can you repeat please?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 97, 1,0,'Bisakah Anda bicara lebih pelan?','Can you speak more slowly?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 98, 1,0,'Bisakah Anda tulis?','Can you write it down?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6, 99, 1,0,'Apakah Anda mengerti apa yang saya ucapkan?','Did you understand what I said?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,100, 1,0,'Saya tidak mengerti.','I don''t understand.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,101, 1,0,'Saya tidak tahu.','I don''t know.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,102, 1,0,'Apakah itu dalam bahasa Indonesia?','What is that called in Indonesian?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,103, 1,0,'Apakah arti kata itu dalam bahasa Inggris?','What does that word mean in English?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,104, 1,0,'Bahasa Indonesianya "thank you" itu apa?','How do you say "thanks" in Indonesian?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,105, 1,0,'Apa ini?','What is this?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,106, 1,0,'Bahasa Indonesia saya jelek.','My Indonesian is bad.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,107, 1,0,'Jangan kuatir.','Don''t worry.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,108, 1,0,'Saya setuju dengan Anda.','I agree with you.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,109, 1,0,'Apa itu benar?','Is that right?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,110, 1,0,'Apa itu salah?','is that wrong?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,111, 1,0,'Apa yang harus saya katakan?','What should I say?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,112, 1,0,'Saya hanya perlu berlatih.','I just need to practice.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,113, 1,0,'Bahasa Indonesia Anda bagus.','Your Indonesian is good.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,114, 1,0,'Saya punya aksen.','I have an accent.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,115, 1,0,'Anda tidak punya aksen.','You don''t have an accent.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,116, 1,0,'Permisi.','Excuse me.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,117, 1,0,'Saya tersesat.','I''m lost.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,118, 1,0,'Bisa tolong saya?','Can you help me?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,119, 1,0,'Bisa saya bantu.','Can I help you?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,120, 1,0,'Saya bukan dari daerah sini.','I''m not from here.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,121, 1,0,'Bagaimana caranya ke Ubud?','How can I get to Ubud?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,122, 1,0,'Lurus.','Go straight.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,123, 1,0,'Lalu.','Then');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,124, 1,0,'Belok kiri.','Turn left');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,125, 1,0,'Belok kanan','Turn right');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,126, 1,0,'Bisakah Anda kasih tunjuk?','Can you show me?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,127, 1,0,'Saya bisa kasih tunjuk.','I can show you.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,128, 1,0,'Ikutlah dengan saya.','Come with me.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,129, 1,0,'Berapa lama dari sini ke sana?','How long does it take to get there?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,130, 1,0,'Pusat kota','Downtown');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,131, 1,0,'Kota bersejarah','Historic center');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,132, 1,0,'Dekat dari sini.','It''s near here.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,133, 1,0,'jauh dari sini.','It''s far form here.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,134, 1,0,'Apakah bisa jalan kaki dari sini ke sana?','Is it within walking distance?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,135, 1,0,'Saya mencari Bapak Smith.','I''m looking for Mr. Smith.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,136, 1,0,'Tunggu sebentar.','One moment please.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,137, 1,0,'Dia tidak ada di sini.','He is not here.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,138, 1,0,'Bandara','Airport');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,139, 1,0,'terminal bis','Bus station');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,140, 1,0,'stasiun kereta','train station');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,141, 1,0,'taksi','taxi');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,142, 1,0,'dekat','near');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,143, 1,0,'jauh','far');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,144, 1,0,'Tolong!','Help!');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,145, 1,0,'Berhenti!','Stop!');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,146, 1,0,'Kebakaran!','Fire!');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,147, 1,0,'Pencuri!','Thief!');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,148, 1,0,'Lari!','Run!');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,149, 1,0,'Awas!','Watch out!');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,150, 1,0,'Panggil polisi!','Call the police!');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,151, 1,0,'Panggil dokter!','Call a doctor!');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,152, 1,0,'Panggil ambulans!','Call the ambulance!');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,153, 1,0,'Anda tidak apa-apa?','Are you okay?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,154, 1,0,'Saya merasa tidak enak.','I feel sick.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,155, 1,0,'Saya perlu doctor.','I need a doctor.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,156, 1,0,'kecelakaan','accident');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,157, 1,0,'keracunan makanan','food poisoning');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,158, 1,0,'Di manakah apotek terdekat?','Where is the closest pharmacy?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,159, 1,0,'Sakit di sini.','It hurts here.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,160, 1,0,'Ini penting!','It''s urgent.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,161, 1,0,'Tenang.','Calm down.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,162, 1,0,'Anda tidak apa-apa?','You will be ok.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,163, 1,0,'Bisakah Anda tolong saya?','Can you help me?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,164, 1,0,'Bisa saya bantu?','Can I help you?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,165, 1,0,'Saya punya reservasi.','I have a reservation.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,166, 1,0,'Apakah ada kamar kosong?','Do you have rooms available?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,167, 1,0,'Dengan shower?','With shower?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,168, 1,0,'Dengan kamar mandi?','With bathroom?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,169, 1,0,'Saya ingin kamar bebas merokok.','I would like a non-smoking room.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,170, 1,0,'Berapakah harga per malamnya.','What is the charge per night?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,171, 1,0,'Saya di sini untuk urusan bisnis.','I''m here on business.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,172, 1,0,'Saya di sini untuk rursan liburan.','I''m here on vacation.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,173, 1,0,'Kotor','Dirty');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,174, 1,0,'Bersih','Clean');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,175, 1,0,'Anda terima kartu kredit?','Do you accept credit cards?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,176, 1,0,'Saya ingin menyewa mobil.','I''d like to rent a car.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,177, 1,0,'Berapa harganya?','How much will it cost?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,178, 1,0,'Minta satu meja untuk satu orang.','A table for one please.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,179, 1,0,'Apakah kursi ini ada orangnya?','Is this seat taken?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,180, 1,0,'Saya vegetarian.','I''m vegetarian.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,181, 1,0,'Saya tidak makan babi.','I don''t eat pork.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,182, 1,0,'Saya tidak minum alkohol.','I don''t drink alcohol.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,183, 1,0,'Apa nama masakan ini?','What''s the name of this dish?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,184, 1,0,'Pelayan','Waiter');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,185, 1,0,'Bisa minta bonnya?','Can we have the check please?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,186, 1,0,'Sangat enak.','It is very delicious.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,187, 1,0,'Saya tidak suka itu.','I don''t like it.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,188, 1,0,'Berapa ini harganya?','How much is this?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,189, 1,0,'Cuma lihat-lihat.','I''m just looking.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,190, 1,0,'Saya tidak punya kembalian.','I don''t have change.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,191, 1,0,'Ini terlalu mahal.','This is too expensive.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,192, 1,0,'mahal','expensive');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,193, 1,0,'murah','cheap');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,194, 1,0,'Jam berapa sekarang?','What time is it?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,195, 1,0,'Jam 3.','It''s 3 o''clock.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,196, 1,0,'Berikan aku ini.','Give me this.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,197, 1,0,'Anda yakin?','Are you sure?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,198, 1,0,'Ambil ini.','Take this.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,199, 1,0,'Dingin sekali.','It''s freezing.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,200, 1,0,'Udaranya dingin.','It''s cold.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,201, 1,0,'Udaranya panas.','It''s hot.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,202, 1,0,'Apakah Anda suka?','Do you like it?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,203, 1,0,'Saya suka sekali.','I really like it.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,204, 1,0,'Saya lapar.','I''m hungry.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,205, 1,0,'Saya haus.','I''m thirsty.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,206, 1,0,'Dia lucu.','He is funny.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,207, 1,0,'di pagi hari','in the morning');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,208, 1,0,'di sore hari','in the evening');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,209, 1,0,'di malam hari','at night');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,210, 1,0,'Cepat.','Hurry up.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,211, 1,0,'Ini tadak masuk akal.','This is nonsense.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,212, 1,0,'Oh Tuhan!','My god!');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,213, 1,0,'Oh tidak!','Oh gosh.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,214, 1,0,'Ini menyebalkan.','It sucks.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,215, 1,0,'Ada apa denganmu?','What''s wrong with you?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,216, 1,0,'Apa kamu gila?','Are you crazy?');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,217, 1,0,'Pergi.','Get lost.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,218, 1,0,'Tinggalkan saya sendiri.','Leave me alone.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,219, 1,0,'Saya tidak tertarik.','I''m not interested.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,220, 1,0,'John yang terkasih','Dear John');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,221, 1,0,'Perjalanan saya sangat menyenangkan.','My trip was very nice.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,222, 1,0,'Budaya dan orang-orangnya sangat menarik.','The culture and people were very interesting.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,223, 1,0,'Saya sangat menikmati waktu bersama Anda.','I had a good time with you.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,224, 1,0,'Saya ingin mengunjungi negara Anda lagi.','I would love to visit your country again.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,225, 1,0,'Jangan lupa tulis surat kepada saya dari waktu ke waktu.','Don''t forget to write me back from time to time.');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,226, 1,0,'waktu','time');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,227, 1,0,'bagus, baik','good');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,228, 1,0,'jelek, buruk','bad');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,229, 1,0,'lumayan','so-so');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,230, 1,0,'besar','big');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,231, 1,0,'kecil','small');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,232, 1,0,'hari ini','today');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(6,233, 1,0,'sekarang','now');
