insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7,  1, 1,0,'noun','jalan', 'road');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7,  2, 1,0,'noun','mobil', 'automobile');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7,  3, 1,0,'noun','sepada', 'bicycle');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7,  4, 1,0,'noun','rumah', 'house');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7,  5, 1,0,'noun','kantor', 'office');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7,  6, 1,0,'noun','sekolah', 'school');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7,  7, 1,0,'noun','toko', 'shop');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7,  8, 1,0,'noun','kebun', 'garden');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7,  9, 1,0,'noun','pohon', 'tree');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 10, 1,0,'noun','anjing', 'dog');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 11, 1,0,'noun','kucing', 'cat');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 12, 1,0,'noun','kuda', 'horse');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 13, 1,0,'noun','kamar', 'room');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 14, 1,0,'noun','meja', 'table');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 15, 1,0,'noun','kursi', 'chair');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 16, 1,0,'noun','lampu', 'lamp');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 17, 1,0,'noun','lemari', 'cupboard');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 18, 1,0,'noun','gelas', 'glass');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 19, 1,0,'noun','jam', 'clock');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 20, 1,0,'noun','buku', 'book');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 21, 1,0,'noun','kertas', 'paper');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 22, 1,0,'noun','pensil', 'pencil');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 23, 1,0,'noun','roti', 'bread');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 24, 1,0,'noun','tas', 'bag');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 25, 1,0,'noun','laki-laki', 'man');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 26, 1,0,'noun','perempuan', 'woman');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 27, 1,0,'noun','anak', 'child');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 28, 1,0,'noun','anak laki-laki', 'boy');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 29, 1,0,'noun','anak perempuan', 'girl');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 30, 1,0,'noun','ayah', 'father');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 31, 1,0,'noun','ibu', 'mother');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 32, 1,0,'noun','abang', 'elder brother');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 33, 1,0,'noun','kakak', 'elder sister or brother');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 34, 1,0,'noun','adik', 'younger brother or sister');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 35, 1,0,'noun','guru', 'teacher');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 36, 1,0,'noun','murid', 'pupil');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 37, 1,0,'noun','pelayan', 'waiter');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 38, 1,0,'noun','pembantu', 'servant');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 39, 1,0,'noun','polisi', 'policeman');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 40, 1,0,'noun','supir', 'driver');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 41, 1,0,'noun','tukang', 'workman');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 42, 1,0,'noun','gereja', 'church');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 43, 1,0,'noun','kunci', 'key');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 44, 1,0,'noun','atap', 'roof');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 45, 1,0,'noun','batu', 'stone');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 46, 1,0,'noun','bensin', 'petrol');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 47, 1,0,'noun','jam', 'clock, watch');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 48, 1,0,'noun','gunting', 'scissors');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 49, 1,0,'noun','jendela', 'window');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 50, 1,0,'noun','kaca', 'glass, pane');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 51, 1,0,'noun','kain', 'cloth, material');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 52, 1,0,'noun','kuda', 'horse');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 53, 1,0,'noun','pagar', 'fence');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 54, 1,0,'noun','pisau', 'knife');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 55, 1,0,'noun','tanah', 'earth');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 56, 1,0,'noun','warung', 'small shop, stall, stand');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 57, 1,0,'noun','susu', 'milk');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 58, 1,0,'noun','mentega', 'butter');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 59, 1,0,'noun','kentang', 'potato');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 60, 1,0,'noun','air', 'water');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 61, 1,0,'noun','keranjang', 'basket');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 62, 1,0,'noun','kotak', 'box');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 63, 1,0,'adj','biru', 'blue');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 64, 1,0,'adj','merah', 'red');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 65, 1,0,'adj','kuning', 'yellow');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 66, 1,0,'adj','hitam', 'black');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 67, 1,0,'adj','putih', 'white');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 68, 1,0,'adj','jingga', 'pink');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 69, 1,0,'adj','coklat', 'brown');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 70, 1,0,'adj','jigau', 'green');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 71, 1,0,'adj','ungu', 'purple');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 72, 1,0,'adj','abu-abu', 'gray');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 73, 1,0,'adj','ahit', 'bitter');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 74, 1,0,'adj','manis', 'sweet');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 75, 1,0,'adj','asam', 'sour');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 76, 1,0,'adj','tawar', 'plain');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 77, 1,0,'adj','asin', 'salty');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 78, 1,0,'adj','enak', 'nice');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 79, 1,0,'adj','lezat', 'delicious');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 80, 1,0,'adj','segar', 'fresh');
insert into flash.quest(programid, seq, lesson, conversation, quest, answer) values(7, 81, 1,0,'adj','nikmat', 'tasty');
