g.data.vocab = [
	{host:'dummy', eng:'zero entry', part:'unk'},
	{host:'apa', eng:'what', part:'unk'},
	{host:'anda', eng:'you', part:'pro'},
	{host:'saya', eng:'I, me', part:'pro'},
	{host:'makan', eng:'eat', part:'vrb'},
	{host:'sama', eng:'same', part:'unk'},
	{host:'selamat', eng:'greeting', part:'unk'},
	{host:'meja', eng:'table', part:'nun'},
	{host:'pagi', eng:'morning', part:'nun'},
	{host:'ini', eng:'this', part:'dem'},
	{host:'roti', eng:'bread', part:'nun'},
	{host:'besok', eng:'tomorrow', part:'adv'},
	{host:'itu', eng:'that', part:'dem'},
	{host:'jumpa', eng:'meet', part:'vrb'},
	{host:'sampai', eng:'until', part:'adv'},
	{host:'baik', eng:'good', part:'adj'},
	{host:'cantik', eng:'beautiful', part:'adj'},
	{host:'cuaca', eng:'weather', part:'nun'},
	{host:'guru', eng:'teacher', part:'nun'},
	{host:'dengar', eng:'listen', part:'vrb'},
	{host:'dengan', eng:'with', part:'prp'},
	{host:'gamelan', eng:'gamelan', part:'nun'},
	{host:'mangga', eng:'mango', part:'nun'},
	{host:'sore', eng:'afternoon', part:'nun'},
	{host:'kabar', eng:'news', part:'nun'},
	{host:'halo', eng:'hello', part:'unk'},
	{host:'boleh', eng:'may', part:'unk'},
	{host:'jalan', eng:'road', part:'nun'},
	{host:'mobil', eng:'automobile', part:'nun'},
	{host:'sepeda', eng:'bicycle', part:'nun'},
	{host:'rumah', eng:'house', part:'nun'},
	{host:'kantor', eng:'office', part:'nun'},
	{host:'sekolah', eng:'school', part:'nun'},
	{host:'toko', eng:'shop', part:'nun'},
	{host:'kebun', eng:'garden', part:'nun'},
	{host:'pohon', eng:'tree', part:'nun'},
	{host:'anjing', eng:'dog', part:'nun'},
	{host:'kucing', eng:'cat', part:'nun'},
	{host:'kuda', eng:'horse', part:'nun'},
	{host:'kamar', eng:'room', part:'nun'},
	{host:'meja', eng:'table', part:'nun'},
	{host:'kursi', eng:'chair', part:'nun'},
	{host:'lampu', eng:'lamp', part:'nun'},
	{host:'lemari', eng:'cupboard', part:'nun'},
	{host:'gelas', eng:'glass', part:'nun'},
	{host:'jam', eng:'clock', part:'nun'},
	{host:'buku', eng:'book', part:'nun'},
	{host:'kertas', eng:'paper', part:'nun'},
	{host:'pensil', eng:'pencil', part:'nun'},
	{host:'roti', eng:'bread', part:'nun'},
	{host:'tas', eng:'bag', part:'nun'},
	{host:'laki-laki', eng:'man', part:'nun'},
	{host:'perempuan', eng:'woman', part:'nun'},
	{host:'anak', eng:'child', part:'nun'},
	{host:'anak laki-laki', eng:'boy', part:'nun'},
	{host:'anak perempuan', eng:'girl', part:'nun'},
	{host:'ayah', eng:'father', part:'nun'},
	{host:'ibu', eng:'mother', part:'nun'},
	{host:'abang', eng:'elder brother', part:'nun'},
	{host:'kakak', eng:'elder sibling', part:'nun'},
	{host:'adik', eng:'younger sibling', part:'nun'},
	{host:'murid', eng:'pupil', part:'nun'},
	{host:'pelayan', eng:'waiter', part:'nun'},
	{host:'pembantu', eng:'servant', part:'nun'},
	{host:'polisi', eng:'policeman', part:'nun'},
	{host:'supir', eng:'driver', part:'nun'},
	{host:'tukang', eng:'workman', part:'nun'},
	{host:'gereja', eng:'church', part:'nun'},
	{host:'warung', eng:'small shop', part:'nun'},
	{host:'kunci', eng:'key', part:'nun'},
	{host:'atap', eng:'roof', part:'nun'},
	{host:'batu', eng:'stone', part:'nun'},
	{host:'jendela', eng:'window', part:'nun'},
	{host:'pagar', eng:'fence', part:'nun'},
	{host:'bensin', eng:'petrol', part:'nun'},
	{host:'tanah', eng:'earth', part:'nun'},
	{host:'kuda', eng:'horse', part:'nun'},
	{host:'jam', eng:'clock, watch', part:'nun'},
	{host:'gunting', eng:'scissors', part:'nun'},
	{host:'kaca', eng:'glass, pane', part:'nun'},
	{host:'kain', eng:'cloth, material', part:'nun'},
	{host:'pisau', eng:'knife', part:'nun'},
	{host:'keranjang', eng:'basket', part:'nun'},
	{host:'kotak', eng:'box', part:'nun'},
	{host:'susu', eng:'milk', part:'nun'},
	{host:'mentega', eng:'butter', part:'nun'},
	{host:'kentang', eng:'potato', part:'nun'},
	{host:'air', eng:'water', part:'nun'},
	{host:'hitam', eng:'black', part:'col'},
	{host:'putih', eng:'white', part:'col'},
	{host:'coklat', eng:'brown', part:'col'},
	{host:'biru', eng:'blue', part:'col'},
	{host:'jigau', eng:'green', part:'col'},
	{host:'merah', eng:'red', part:'col'},
	{host:'kuning', eng:'yellow', part:'col'},
	{host:'jingga', eng:'pink', part:'col'},
	{host:'ungu', eng:'purple', part:'col'},
	{host:'abu-abu', eng:'gray', part:'col'},
	{host:'enak', eng:'delicious', part:'tas'},
	{host:'manis', eng:'sweet', part:'tas'},
	{host:'pedas', eng:'spicy', part:'tas'},
	{host:'asam', eng:'sour', part:'tas'},
	{host:'asin', eng:'salty', part:'tas'},
	{host:'lezat', eng:'delicious', part:'tas'},
	{host:'segar', eng:'fresh', part:'tas'},
	{host:'nikmat', eng:'tasty', part:'tas'},
	{host:'ahit', eng:'bitter', part:'tas'},
	{host:'tawar', eng:'plain', part:'tas'},
	{host:'besar', eng:'big', part:'adj'},
	{host:'kecil', eng:'small', part:'adj'},
	{host:'cepat', eng:'fast', part:'adj'},
	{host:'lambat', eng:'slow', part:'adj'},
	{host:'hebat', eng:'great', part:'adj'},
	{host:'mahal', eng:'expensive', part:'adj'},
	{host:'murah', eng:'cheap', part:'adj'},
	{host:'baik', eng:'good', part:'adj'},
	{host:'pintar', eng:'smart', part:'adj'},
	{host:'sakit', eng:'sick', part:'adj'},
	{host:'dingin', eng:'cold', part:'adj'},
	{host:'panas', eng:'hot', part:'adj'},
	{host:'banyak', eng:'many', part:'adj'},
	{host:'sedikit', eng:'few', part:'adj'},
	{host:'pendek', eng:'short', part:'adj'},
	{host:'tinggi', eng:'tall', part:'adj'},
	{host:'baru', eng:'new', part:'adj'},
	{host:'rusak', eng:'broken', part:'adj'},
	{host:'penumpang', eng:'passenger', part:'nun'},
	{host:'parkir', eng:'parking lot', part:'nun'},
	{host:'perpastakan', eng:'library', part:'nun'},
	{host:'tutup', eng:'lid', part:'nun'},
	{host:'desa', eng:'village', part:'nun'},
	{host:'kota', eng:'city', part:'nun'},
	{host:'negara', eng:'nation', part:'nun'},
	{host:'sangat', eng:'very', part:'qty'},
	{host:'sekali', eng:'very', part:'adj'},
	{host:'sabun', eng:'soap', part:'nun'},
	{host:'mandi', eng:'to bathe', part:'vrb'},
	{host:'cuci', eng:'to wash', part:'vrb'},
	{host:'belajar', eng:'to study', part:'vrb'},
	{host:'kolam', eng:'pool', part:'nun'},
	{host:'renang', eng:'to swim', part:'vrb'},
	{host:'tidur', eng:'to sleep', part:'vrb'},
	{host:'mandi', eng:'to bathe', part:'vrb'},
	{host:'ruang', eng:'space', part:'nun'},
	{host:'operasi', eng:'to operate', part:'vrb'},
	{host:'papan', eng:'board', part:'nun'},
	{host:'tulis', eng:'to write', part:'vrb'},
	{host:'kotor', eng:'dirty', part:'adj'},
	{host:'bersih', eng:'clean', part:'adj'},
	{host:'panas', eng:'hot', part:'adj'},
	{host:'dingin', eng:'cold', part:'adj'},
	{host:'suka', eng:'like', part:'vrb'},
	{host:'mau', eng:'to want', part:'vrb'},
	{host:'perlu', eng:'to need', part:'vrb'},
	{host:'baca', eng:'to read', part:'vrb'},
	{host:'menulis', eng:'to write', part:'vrb'},
	{host:'mandi', eng:'to bathe', part:'vrb'},
	{host:'jual', eng:'to sell', part:'vrb'},
	{host:'lihat', eng:'to see, to look at', part:'vrb'},
	{host:'duduk', eng:'to sit', part:'vrb'},
	{host:'berdiri', eng:'to stand', part:'vrb'},
	{host:'tinggal', eng:'to live, to stay', part:'vrb'},
	{host:'datang', eng:'to come', part:'vrb'},
	{host:'jalan', eng:'to walk', part:'vrb'},
	{host:'berjalan', eng:'to walk', part:'vrb'},
	{host:'menjalan', eng:'to run', part:'vrb'},
	{host:'pergi', eng:'to go', part:'vrb'},
	{host:'kembali', eng:'to return', part:'vrb'},
	{host:'menunggu', eng:'to wait', part:'vrb'},
	{host:'berhenti', eng:'to stop', part:'vrb'},
	{host:'beristirahat', eng:'to rest', part:'vrb'},
	{host:'menyopir', eng:'to drive', part:'vrb'},
	{host:'tahu', eng:'to know', part:'vrb'},
	{host:'ingat', eng:'to remember', part:'vrb'},
	{host:'lupa', eng:'to forget', part:'vrb'},
	{host:'makan', eng:'to eat', part:'vrb'},
	{host:'minum', eng:'to drink', part:'vrb'},
	{host:'masuk', eng:'to come in', part:'vrb'},
	{host:'mulai', eng:'to start, begin', part:'vrb'},
	{host:'punya', eng:'to have', part:'vrb'},
	{host:'berbicara', eng:'to speak', part:'vrb'},
	{host:'tidur', eng:'to sleep', part:'vrb'},
	{host:'bangun', eng:'to wake up', part:'vrb'},
	{host:'belajar', eng:'to study', part:'vrb'},
	{host:'bekerja', eng:'to work', part:'vrb'},
	{host:'bermain', eng:'to play', part:'vrb'},
	{host:'mengunci', eng:'to lock', part:'vrb'},
	{host:'sedang', eng:'currently', part:'adv'},
	{host:'akan', eng:'will', part:'adv'},
	{host:'sudah', eng:'already', part:'adv'},
	{host:'belum', eng:'not yet', part:'adv'},
	{host:'pernak', eng:'ever', part:'adv'},
	{host:'marih', eng:'still', part:'adv'},
	{host:'ingin', eng:'want', part:'adv'},
	{host:'harus', eng:'must', part:'adv'},
	{host:'perlu', eng:'necessary, need', part:'adv'},
	{host:'saka', eng:'like', part:'adv'},
	{host:'boleh', eng:'may', part:'adv'},
	{host:'dapat', eng:'can', part:'adv'},
	{host:'mungkin', eng:'maybe', part:'adv'},
	{host:'sangat', eng:'very', part:'adv'},
	{host:'agak', eng:'so-so', part:'adv'},
	{host:'cukup', eng:'enough', part:'adv'},
	{host:'bercermin', eng:'to reflect, to mirror', part:'vrb'},
	{host:'dengar', eng:'to hear', part:'vrb'},
	{host:'gendong', eng:'to carry', part:'vrb'},
	{host:'keluar', eng:'to go out', part:'vrb'},
	{host:'pulang', eng:'to go home', part:'vrb'},
	{host:'jatuh', eng:'to fall', part:'vrb'},
	{host:'berangat', eng:'to leave', part:'vrb'},
	{host:'berati', eng:'to mean', part:'vrb'},
	{host:'berbelanja', eng:'to shop', part:'vrb'},
	{host:'bercerita', eng:'to tell (a story)', part:'vrb'},
	{host:'berdoa', eng:'to pray', part:'vrb'},
	{host:'berhasil', eng:'to succeed', part:'vrb'},
	{host:'berkata', eng:'to say, to tell', part:'vrb'},
	{host:'berlari', eng:'to run', part:'vrb'},
	{host:'berpikir', eng:'to think', part:'vrb'},
	{host:'berenang', eng:'to swim', part:'vrb'},
	{host:'bersembunyi', eng:'to hide', part:'vrb'},
	{host:'bertanya', eng:'to ask', part:'vrb'},
	{host:'bertemu', eng:'to meet', part:'vrb'},
	{host:'membawa', eng:'to bring, carry', part:'vrb'},
	{host:'membuka', eng:'to open', part:'vrb'},
	{host:'membeli', eng:'to buy', part:'vrb'},
	{host:'memakai', eng:'to wear, use', part:'vrb'},
	{host:'memotong', eng:'to cut', part:'vrb'},
	{host:'meminjam', eng:'to borrow', part:'vrb'},
	{host:'melihat', eng:'to see, to lookat', part:'vrb'},
	{host:'melompat', eng:'to jump', part:'vrb'},
	{host:'memasak', eng:'to cook', part:'vrb'},
	{host:'meminta', eng:'to ask for something', part:'vrb'},
	{host:'menikah', eng:'to marry', part:'vrb'},
	{host:'menyanyi', eng:'to sing', part:'vrb'},
	{host:'merusak', eng:'to break', part:'vrb'},
	{host:'merasa', eng:'to feel', part:'vrb'},
	{host:'mencuci', eng:'to wash', part:'vrb'},
	{host:'mencoba', eng:'to try', part:'vrb'},
	{host:'mendorong', eng:'to push', part:'vrb'},
	{host:'mendengar', eng:'to hear', part:'vrb'},
	{host:'menjadi', eng:'to become', part:'vrb'},
	{host:'menjawab', eng:'to answer', part:'vrb'},
	{host:'mengambil', eng:'to take', part:'vrb'},
	{host:'mengimpor', eng:'to import', part:'vrb'},
	{host:'menggoreng', eng:'to fry', part:'vrb'},
	{host:'mengganggu', eng:'to disturb', part:'vrb'},
	{host:'mengharap', eng:'to hope', part:'vrb'},
	{host:'menghitun', eng:'to count', part:'vrb'},
	{host:'mengetik', eng:'to type', part:'vrb'},
	{host:'menyimpan', eng:'to keep', part:'vrb'},
	{host:'menyuruh', eng:'to command', part:'vrb'},
	{host:'mengecat', eng:'to paint', part:'vrb'},
	{host:'mengebom', eng:'to bomb', part:'vrb'},
	{host:'mengecek', eng:'to check', part:'vrb'},
	{host:'mengepel', eng:'to mop', part:'vrb'},
	{host:'anda', eng:'your', part:'pos'},
	{host:'saya', eng:'my', part:'pos'},
	{host:'dia', eng:'his', part:'pos'},
	{host:'mereka', eng:'their', part:'pos'},
	{host:'kita', eng:'our', part:'pos'}
];
g.sengen.onVocabLoaded();
