insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1,  1, 'a', 'v', 'A a', 'u like in the word fun');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1,  2, 'a', 'v', 'Á á', 'a like in the word father');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1,  3, 'a', 'v', 'E e', 'e like in the word red');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1,  4, 'a', 'v', 'É é', 'ai like in the word pair');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1,  5, 'a', 'v', 'Ě ě', 'ye like in the word yes');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1,  6, 'a', 'v', 'I i', 'i like in the word fit');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1,  7, 'a', 'v', 'Í í', 'ee like in the word bee');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1,  8, 'a', 'v', 'O o', 'o like in the word hot');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1,  9, 'a', 'v', 'Ó ó', 'oo like in the word door');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1, 10, 'a', 'v', 'U u', 'u like in the word push');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1, 11, 'a', 'v', 'Ú ú', 'oo like in the word fool');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1, 12, 'a', 'v', 'Ů ů', 'oo like in the word fool');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1, 13, 'a', 'c', 'B b', 'b like in the word bat');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1, 14, 'a', 'c', 'C c', 'ts like in the word bits');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1, 15, 'a', 'c', 'Č č', 'ch like in the word chat');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1, 16, 'a', 'c', 'D d', 'd like in the word dog');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1, 17, 'a', 'c', 'Ď ď', 'dy sound like "du" in duel');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1, 18, 'a', 'c', 'F f', 'f like in the word far');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1, 19, 'a', 'c', 'G g', 'g like in the word gap');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   1, 20, 'a', 'c', 'H h', 'h like in the word hot');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2,  1, 'a', 'c', 'CH ', 'ch like in the word loch, aspirate');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2,  2, 'a', 'c', 'J j', 'y like in the word yes');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2,  3, 'a', 'c', 'K k', 'k like in the word kit');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2,  4, 'a', 'c', 'L l', 'l like in the word lip');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2,  5, 'a', 'c', 'M m', 'm like in the word mat');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2,  6, 'a', 'c', 'N n', 'n like in the word nut');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2,  7, 'a', 'c', 'Ň ň', 'ny sound like "n" in onion');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2,  8, 'a', 'c', 'P p', 'p like in the word pin');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2,  9, 'a', 'c', 'R r', 'r like in the word rat, but rolled');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2, 10, 'a', 'c', 'Ř ř', 'rž sound like "rg" in bourgois');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2, 11, 'a', 'c', 'S s', 's like in the word sun');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2, 12, 'a', 'c', 'Š š', 'sh like in the word ship');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2, 13, 'a', 'c', 'T t', 't like in the word top');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2, 14, 'a', 'c', 'Ť ť', 'ty sound like "tu" in tune');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2, 15, 'a', 'c', 'V v', 'v like in the word vat');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2, 16, 'a', 'c', 'Y y', 'i like in the word bit');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2, 17, 'a', 'c', 'Ý ý', 'ee like in the word bee');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2, 18, 'a', 'c', 'Z z', 'z like in the word zip');
insert into bahasa.card(programid, level, seq, part, subpart, quest, answer) values( 4,   2, 19, 'a', 'c', 'Ž ž', 'zh sound like "s" in treasure');

insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3,  1, 'ano', 'yes');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3,  2, 'ne', 'no');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3,  3, 'prosim', 'please');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3,  4, 'děkuji', 'I thank you');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3,  5, 'děkujeme', 'we thank you');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3,  6, 'za platím', 'may I pay');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3,  7, 'budu platit', 'I will pay');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3,  8, 'ještě kávu', 'more coffee');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3,  9, 'dobrý den', 'good day');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3, 10, 'na shledanou', 'good bye');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3, 11, 'nápodobně', 'you too');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3, 12, 'dobrou chuť', 'good appetite');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3, 13, 'pardon', 'sorry. excuse me.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3, 14, 'bohužel', 'unfortunately');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3, 15, 'nesmysl', 'nonsense');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3, 16, 's dovolením', 'with allowness');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3, 17, 'hezký den', 'nice day');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3, 18, 'hezký týden', 'nice evening.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3, 19, 'hezký víkend', 'nice weekend.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   3, 20, 'Měj se dobře!', 'Have a nice day!');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4,  1, 'To je', 'It is');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4,  2, 'To je nesmysl', 'It is nonsense.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4,  3, 'a', 'and');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4,  4, 'ale', 'but');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4,  5, 'taky', 'also');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4,  6, 'nebo', 'or');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4,  7, 'tak', 'so');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4,  8, 'snídaně', 'breakfast');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4,  9, 'Praha', 'Prague');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4, 10, 'čestina', 'Czech language');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4, 11, 'nový', 'new');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4, 12, 'starý', 'old');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4, 13, 'město', 'town, city');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4, 14, 'náměstí', 'square');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4, 15, 'nové město', 'new town');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4, 16, 'staré Město', 'old town');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4, 17, 'Staroměstské náměstí', 'old town square');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4, 18, 'národní', 'national');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4, 19, 'divadlo', 'theatre');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   4, 20, 'národní divadlo', 'national theatre');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5,  1, 'radnice', 'town hall');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5,  2, 'příští zastávka', 'next stop');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5,  3, 'nádraží', 'station');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5,  4, 'Václav', 'Wenceslas');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5,  5, 'Karlovo', 'Charles');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5,  6, 'Smetana', 'Smetana (composer)');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5,  7, 'Dvořák', 'Dvorak (composer)');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5,  8, 'Jak se jmenujete?', 'How do you name yourself?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5,  9, 'Jmenuji se John', 'My name is John');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5, 10, 'Jsem John', 'I am John');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5, 11, 'To je John', 'This is John.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5, 12, 'antikvariát', 'used and antique books, stamps, prints');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5, 13, 'bižuterie', 'costume jewelry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5, 14, 'domácí potřeby', 'household items ');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5, 15, 'drogerie', 'drugstore (Czech drugstores do not carry drugs and medications)');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5, 16, 'hračky', 'toys');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5, 17, 'klenoty / klenotnictví', 'jewelry store');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5, 18, 'knihy / knihkupectví', 'books / bookstore');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5, 19, 'korálky', 'beads');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   5, 20, 'lékárna', 'pharmacy');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   6,  1, 'nákupní centrum / galerie', 'shopping center / mall');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   6,  2, 'obchodní dům', 'department store');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   6,  3, 'opravna', 'repair shop');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   6,  4, 'ovoce a zelenina', 'fruits and vegetables');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   6,  5, 'papírnictví', 'paper products (school and office needs, wrapping paper, etc.)');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   6,  6, 'pečivo / pekárna / pekařství', 'bakery');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   6,  7, 'potraviny', 'grocery store');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   6,  8, 'sklo, porcelán', 'glass and china');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   6,  9, 'starožitnictví', 'antique shop');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   6, 10, 'suvenýry', 'souvenirs');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   6, 11, 'tržnice', 'market, market hall');
insert into bahasa.card(programid, level, seq, quest, answer) values( 4,   6, 12, 'železářství', 'hardware store');
