insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1,  1, 'hola', 'hello');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1,  2, 'adios', 'goodbye');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1,  3, 'lapiz', 'pencil');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1,  4, 'estudiar', 'study');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1,  5, 'Yo estudiar Español', 'I study Spanish');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1,  6, 'Español', 'Spanish');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1,  7, 'la madre', 'the mother');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1,  8, 'el padre', 'the father');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1,  9, 'el hermano', 'the brother');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1, 10, 'la hermana', 'the sister');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1, 11, 'el muchacho', 'the boy');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1, 12, 'la muchacha', 'the girl');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1, 13, 'la lámpara', 'the lampa');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1, 14, 'el teléfono', 'the telephone');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1, 15, 'la ventana', 'the window');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1, 16, 'el televisor', 'the television');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1, 17, 'la mesa', 'the table');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1, 18, 'el disco compacto', 'the compact disk');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1, 19, 'la puerta', 'the door');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   1, 20, 'la cocina', 'the kitchen');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2,  1, 'el radio', 'the radio');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2,  2, 'el gato', 'the cat');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2,  3, 'la flor', 'the flower');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2,  4, 'la sala', 'the living room');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2,  5, '¿Es la teléfono?', 'Is it the telephone?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2,  6, 'Es...', 'It is...');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2,  7, 'No es...', 'It is not...');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2,  8, 'No.  No es la teléfono.', 'No. It is not the telephone.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2,  9, '¿Qué?', 'What?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2, 10, '¿Quién', 'Who?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2, 11, '¿Dónde?', 'When?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2, 12, '¿Cómo es ...?', 'What is ... like?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2, 13, 'un mapa', 'a map');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2, 14, 'una frase', 'a sentence');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2, 15, 'la pizara', 'the blackboard');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2, 16, 'una tiza', 'a piece of chalk');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2, 17, 'un borrador', 'an eraser');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2, 18, 'la clase de español', 'the spanish class');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2, 19, 'el profesor', 'the professor');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   2, 20, 'la profesora', 'the (female) professor');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3,  1, 'una mesa', 'a table');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3,  2, 'una silla', 'a chair');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3,  3, 'una fruta', 'a fruit');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3,  4, 'una alumna', 'a (female) student');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3,  5, 'un alumno', 'a (male) student');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3,  6, 'un pupetre', 'a desk');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3,  7, 'un lápiz', 'a pencil');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3,  8, 'una pluma', 'a pen');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3,  9, 'un libro', 'a book');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3, 10, 'un papel', 'a paper');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3, 11, 'un cuaderno', 'a notebook');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3, 12, 'un salón de clase', 'a classroom');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3, 13, 'una escuela', 'a school');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3, 14, 'un escritorio', 'a desk');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3, 15, '¿Que es esto?', 'What is this?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3, 16, '¿Que es...?', 'What is ...?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3, 17, '¿Quién es...?', 'Who is...?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3, 18, 'el autobús', 'the bus');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3, 19, 'la cuidad', 'the city');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   3, 20, 'el banco', 'the bank');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4,  1, 'el avión', 'the airplane');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4,  2, 'el ciné', 'the cinima');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4,  3, 'el edificio', 'the building');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4,  4, 'el policia', 'the policeman');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4,  5, 'el ladrón', 'the thief');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4,  6, 'la calle', 'the street');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4,  7, 'la revista', 'the magazine');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4,  8, 'el periódico', 'the newspaper');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4,  9, 'la tienda', 'the store');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4, 10, 'el perro', 'the dog');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4, 11, 'la mujer', 'the woman');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4, 12, 'el hombre', 'the man');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4, 13, 'el automóvile', 'the car');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4, 14, 'el carro', 'the car');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4, 15, 'el coche', 'the car');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4, 16, 'los alimentos', 'the foods');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4, 17, 'la cliente', 'the customer');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4, 18, 'el cajero', 'the clerk');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4, 19, 'el café', 'the coffee');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   4, 20, 'jugo de naranja', 'orange juice');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5,  1, 'las manzanas', 'the apples');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5,  2, 'el pan', 'the bread');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5,  3, 'en liquidación', 'liquidation');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5,  4, 'el dependiente', 'dependent');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5,  5, 'las botellas de leche', 'the bottles of milk');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5,  6, 'las naranjas', 'the oranges');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5,  7, 'helado de vainilla', 'vanilla ice cream');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5,  8, 'helado de chocolate', 'chocolate ice cream');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5,  9, 'los dulces', 'the candies');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5, 10, 'la mantequilla', 'the butter');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5, 11, 'los huevos', 'the eggs');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5, 12, 'el queso', 'the cheese');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5, 13, '¿Que compra usted?', 'What are you buying?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5, 14, 'Compor alimentos.', 'I am buying food.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5, 15, 'Compra naranja.', 'I am buying oranges.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5, 16, 'Compra queso.', 'I am buying cheese.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5, 17, '¿Compra usted café?', 'Are you buying coffee?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5, 18, 'No compro café.', 'I am not buying coffee.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5, 19, 'preguntas', 'questions');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   5, 20, 'modelo', 'model');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6,  1, 'estudia', 'study');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6,  2, 'mira', 'looks');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6,  3, 'escribe', 'write');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6,  4, 'lee', 'read');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6,  5, 've', 'sees');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6,  6, 'corre', 'run');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6,  7, 'come', 'eat');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6,  8, 'bebe', 'drink');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6,  9, 'pregunta', 'teach');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6, 10, 'contesta', 'ask');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6, 11, 'canta', 'sing');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6, 12, 'eschucha', 'listen');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6, 13, 'baila', 'dance');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6, 14, 'trabaja', 'work');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6, 15, 'van', 'go');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6, 16, 'camina', 'walk');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6, 17, 'descansa', 'rests');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6, 18, 'sale', 'leave');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6, 19, 'pone', 'turns on');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   6, 20, 'El alumno estudia la lección.', 'The student studies the lexicon.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7,  1, 'El padre mira la televison.', 'The father watches the television.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7,  2, 'La muchacha escribe la frase.', 'The girl writes the sentence.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7,  3, 'La alumna lee la revista.', 'The student reads the magazine.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7,  4, 'El policía ve el accidente.', 'The policeman sees the accident.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7,  5, 'El hombre corre en la calle.', 'The man runs in the street.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7,  6, 'La mujer come helado.', 'The woman eats ice cream.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7,  7, 'El muchacho bebe leche.', 'The boy drinks milk.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7,  8, 'El professor pregunta.', 'The professor asks questions.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7,  9, 'El alumno contesta mucho.', 'The student answers much.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7, 10, 'La señorita canta.', 'The Miss sings.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7, 11, 'El señor escucha la radio.', 'The Mr. listens to the radio.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7, 12, 'La hermana baila.', 'The sister dances.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7, 13, 'El padre trabaja.', 'The father works.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7, 14, 'Las mujeres van a la tienda.', 'The women go to the store.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7, 15, 'La madre compra alimentos.', 'The woman buys food.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7, 16, 'María camina a la escuela.', 'Maria walks to the school.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7, 17, 'Carlos descansa en casa.', 'Carlos rests at home.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7, 18, 'Francisco sale de la casa.', 'Francis leaves the house.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7, 19, 'Antonio pone la televisión.', 'Antonio turns on the television.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   7, 20, '¿Quién escribe en la pizarra?', 'Who writes on the blackboard?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8,  1, '¿Quién come el pan?', 'Who eats the bread?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8,  2, '¿Quién sale de la escuela?', 'Who leaves from the school?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8,  3, '¿Quién bebe la Coca Cola?', 'Who drinks the Coca Cola?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8,  4, '¿Quién lee el periódico?', 'Who reads the newspaper?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8,  5, '¿Mira la mujer la televisión?', 'Does the woman watch television?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8,  6, '¿Canta la muchacha?', 'Does the girl sing?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8,  7, '¿Corre el policia?', 'Does the policeman run?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8,  8, '¿Estudia Carlos?', 'Does Carlos study?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8,  9, '¿Come María el queso?', 'Does Maria eat the cheese?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8, 10, 'fácil', 'easy');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8, 11, 'difícil', 'difficult');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8, 12, 'grande', 'large');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8, 13, 'pequeño', 'small');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8, 14, 'mucho', 'much');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8, 15, 'poco', 'little');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8, 16, 'trabajador', 'worker');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8, 17, 'perezoso', 'lazy');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8, 18, 'allí', 'there');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8, 19, 'aquí', 'here');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   8, 20, 'flaco', 'thin');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9,  1, 'gordo', 'fat');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9,  2, 'bonito', 'pretty');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9,  3, 'feo', 'ugly');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9,  4, 'viejo', 'old');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9,  5, 'joven', 'young');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9,  6, '¿Cómo es Fifi?', 'How is Fifi like?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9,  7, 'Fifí es bonita. Fifí no es fea.', 'Fifi is pretty.  Fifi is not ugly.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9,  8, '¿Cómo es el hombre? El hombre es grande.', 'How is the man like? The man is large.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9,  9, '¿Cómo es la lección? La lección is difícil.', 'How is the lexicon?  The lexicon is difficult.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9, 10, '¿Cómo es el professor.  El professor es viejo.', 'How is the professor like? The professor is old.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9, 11, '¿Cómo es el alumno? El alumno is gordo.', 'How is the student like? The student is fat.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9, 12, '¿Cómo es la madre? La madre es trabajador.', '¿How is the mother like? The mother is hard-working.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9, 13, '¿Es pequeño el elefante?  No. El elefante no es pequeño. El elefante es grande.', 'Is the elefant small?  No, the elefant is not small.  The elefant is large.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9, 14, '¿Hay pocos alumnos en la clase? No. Hay mucho alumnos en la clase?', 'Are there a few students in the class?  No.  There are many students in the class.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9, 15, 'fácil', 'easy');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9, 16, 'difícil', 'difficult');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9, 17, 'grande', 'large');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9, 18, 'pequeño', 'small');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9, 19, 'mucho', 'much');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,   9, 20, 'poco', 'little');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10,  1, 'trabajador', 'worker');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10,  2, 'perezoso', 'lazy');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10,  3, 'allí', 'there');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10,  4, 'aquí', 'here');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10,  5, 'flaco', 'thin');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10,  6, 'gordo', 'fat');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10,  7, 'bonito', 'pretty');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10,  8, 'feo', 'ugly');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10,  9, 'viejo', 'old');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10, 10, 'joven', 'young');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10, 11, '¿Cómo es Fifi?', 'How is Fifi like?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10, 12, 'Fifí es bonita. Fifí no es fea.', 'Fifi is pretty.  Fifi is not ugly.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10, 13, '¿Cómo es el hombre? El hombre es grande.', 'How is the man like? The man is large.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10, 14, '¿Cómo es la lección? La lección is difícil.', 'How is the lexicon?  The lexicon is difficult.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10, 15, '¿Cómo es el professor.  El professor es viejo.', 'How is the professor like? The professor is old.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10, 16, '¿Cómo es el alumno? El alumno is gordo.', 'How is the student like? The student is fat.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10, 17, '¿Cómo es la madre? La madre es trabajador.', ' How is the mother like? The mother is hard-working.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10, 18, '¿Es pequeño el elefante?  No. El elefante no es pequeño. El elefante es grande.', 'Is the elefant small?  No, the elefant is not small.  The elefant is large.');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10, 19, '¿Hay pocos alumnos en la clase?', 'No. Hay mucho alumnos en la clase?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  10, 20, 'el amor', 'love');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11,  1, 'Carlos', 'Charles');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11,  2, 'Pepita', 'Josie');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11,  3, 'la casa', 'the home');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11,  4, 'en casa', 'at home');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11,  5, 'la cocina', 'the kitchen, the cooking');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11,  6, 'el cuaderno', 'the notebook');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11,  7, 'el diccionario', 'the dictionary');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11,  8, 'la escuela', 'the school');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11,  9, 'el español', 'the Spanish language, Spanish');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11, 10, 'el examen', 'the test');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11, 11, 'mi examen de español', 'my Spanish test');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11, 12, 'la frase', 'the sentence');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11, 13, 'la gramática', 'the grammar');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11, 14, 'el hermano de Pepita', 'Josie''s brother');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11, 15, 'el libro de gramática', 'the grammar gextbook');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11, 16, 'la lección de español', 'the Spanish lesson');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11, 17, 'la noche', 'the evening, the night');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11, 18, 'esta noche', 'tonight, this evening');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11, 19, 'el padre de Pepita', 'Josie''s father');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  11, 20, 'la palabra', 'the word');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12,  1, 'el papel de vocabulario', 'the vocabulary paper');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12,  2, 'la pasión', 'the passion');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12,  3, 'el periódico', 'the newspaper');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12,  4, 'mi programa favorito', 'my favorite program');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12,  5, 'el radio', 'the radio set');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12,  6, 'la radio', 'the radio broadcast');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12,  7, 'la televisión', 'the television ');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12,  8, 'la televisor', 'the TV set');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12,  9, 'la voz', 'the voice');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12, 10, 'estudioso', 'studious');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12, 11, 'fácil', 'easy');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12, 12, 'favorito', 'favorite');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12, 13, 'importante', 'important');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12, 14, 'interesante', 'interesting');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12, 15, 'mi', 'my');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12, 16, 'necesario', 'necessary');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12, 17, 'posible', 'possible');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12, 18, 'su', 'her');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12, 19, 'copia', '(she) copies');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  12, 20, 'entra', '(he) enters');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13,  1, 'es', 'it is, she is');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13,  2, 'no es', 'it is not');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13,  3, 'eschucha', '(she) listens to, is listening to');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13,  4, 'setudia', '(she) studies, is studying');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13,  5, 'estudiar', 'to study');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13,  6, 'habla', 'speaks');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13,  7, 'hay', 'there are, there is');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13,  8, 'lee', '(he) reads, is reading');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13,  9, 'mirar', 'to look at, to watch');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13, 10, 'necesito', 'I need');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13, 11, 'pone la televisión', '(he) turns on the television program');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13, 12, 'quiero', 'I want');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13, 13, 'ahora', 'now');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13, 14, '¡ay, papá!', 'Oh, Daddy!');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13, 15, 'con', 'with');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13, 16, 'de', 'of, in, from');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13, 17, 'ella', 'she');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13, 18, 'en', 'in, into');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13, 19, 'mañana', 'tomorrow');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  13, 20, 'muy', 'very');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14,  1, 'no', 'not, no');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14,  2, 'por favor', 'please');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14,  3, 'sí', 'yes; yes, indeed!');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14,  4, 'también', 'also, too');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14,  5, 'y', 'and');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14,  6, 'yo', 'I');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14,  7, 'el aire', 'the air');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14,  8, 'la aidea', 'the town');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14,  9, 'el año', 'the year');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14, 10, 'la avenida', 'the avenue');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14, 11, 'la calle', 'the street');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14, 12, 'el cine', 'the movie theater');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14, 13, 'la ciudad', 'the city');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14, 14, 'la cosa', 'the thing');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14, 15, 'el dinero', 'the money');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14, 16, 'el edificio', 'the building');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14, 17, 'la experiencia', 'the experience');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14, 18, 'la flor', 'the flower');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14, 19, 'Francisco', 'Frank');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  14, 20, 'Paco', 'Frankie');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15,  1, 'el hombre', 'the man');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15,  2, 'María', 'Mary, Marie');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15,  3, 'la mujer', 'the woman');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15,  4, 'el museo', 'the museum');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15,  5, 'Nueva York', 'New York');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15,  6, 'la oficina', 'the office');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15,  7, 'el parque', 'the park');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15,  8, 'el primo', 'the cousin');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15,  9, 'la prisa', 'the hurra');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15, 10, 'de prisa', 'in a hurry, in a rush');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15, 11, 'el restaurante', 'the restaurant');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15, 12, 'el teatro', 'the theater');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15, 13, 'la tienda', 'the store');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15, 14, 'alto', 'tall, high');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15, 15, 'estos', 'these');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15, 16, 'estas', 'these');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15, 17, 'extraño', 'strange');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15, 18, 'fresco', 'fresh');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15, 19, 'grande', 'large');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  15, 20, 'mucho', 'a great deal of, much');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16,  1, 'muchos', 'many, a great many');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16,  2, 'nuevo', 'new');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16,  3, 'pequeño', 'small, little');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16,  4, 'rápido', 'fast, rapid');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16,  5, 'sus', 'their');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16,  6, 'todos', 'every, all');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16,  7, 'tanto', 'so much');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16,  8, 'tonto', 'foolish');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16,  9, 'comer', 'to eat');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16, 10, 'descansar', 'to rest');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16, 11, 'desea', '(she) wishes, wants');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16, 12, 'hago', 'I do');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16, 13, 'ir', 'to go');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16, 14, 'ganamos', 'we earn');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16, 15, '¡mira!', 'look!');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16, 16, 'mira', '(she) looks at, watches');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16, 17, 'miran', 'they look at, watch');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16, 18, 'respirar', 'to breathe');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16, 19, 'son', '(they) are');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  16, 20, 'trabajar', 'to work');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17,  1, 'van', 'they go, walk');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17,  2, 'ver', 'to see');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17,  3, 'visita', 'she visits');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17,  4, 'visitan', 'they visit');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17,  5, 'vivir', 'to live');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17,  6, 'a', 'to');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17,  7, 'aquí', 'here');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17,  8, 'así', 'in this way, thus');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17,  9, 'cómo', 'how');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17, 10, 'después de', 'after');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17, 11, 'eso', 'that');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17, 12, 'las', 'the');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17, 13, 'los', 'the');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17, 14, 'o', 'or');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17, 15, 'para', 'for, in order to');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17, 16, 'pero', 'but');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17, 17, 'por', 'along, through');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17, 18, '¿por qué hay...?', 'Why is (are) there ...?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17, 19, 'pues', 'well, then');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  17, 20, 'todo', 'everything, all');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18,  1, 'treinta', 'thirty');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18,  2, 'una', 'a');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18,  3, 'veinte', 'twenty');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18,  4, 'la abuela', 'the grandmother');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18,  5, 'el abuelo', 'the grandfather');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18,  6, 'el actividad', 'the activity');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18,  7, 'el amiguito', 'the little friend');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18,  8, 'el año', 'the year');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18,  9, 'la casa Hernández', 'the Hernandez home');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18, 10, 'el cuarto', 'the room');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18, 11, 'el cumpleaños', 'the birthday');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18, 12, 'el día', 'the day');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18, 13, 'los dulces', 'the candy');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18, 14, 'la familia', 'the family');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18, 15, 'la forma', 'the shape, form');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18, 16, 'José', 'Joseph');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18, 17, 'Joselito', 'Joey');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18, 18, 'el juego', 'the game');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18, 19, 'la música', 'the music');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  18, 20, 'el nene', 'the baby, very young child');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19,  1, 'el niño', 'the child, little boy');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19,  2, 'los padres', 'the parents');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19,  3, 'el pájaro', 'the bird');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19,  4, 'el pedaza', 'the piece');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19,  5, 'la piñata', 'the piñata (paper mache figure filled with candies, etc)');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19,  6, 'los refrescos', 'the refreshments');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19,  7, 'el regalito', 'the little present');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19,  8, 'el regalo', 'the present');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19,  9, 'Sarita', 'little Sarah');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19, 10, 'todo el mondo', 'everyone');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19, 11, 'todos', 'everybody, all');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19, 12, 'la torta de chocolate', 'the chocolate cake');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19, 13, 'el vecino', 'the neighbor');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19, 14, 'la vela', 'the candle');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19, 15, 'ayudar', 'to help');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19, 16, 'bailar', 'to dance');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19, 17, 'bajar', 'to go down');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19, 18, 'buscar', 'to look for');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19, 19, 'caminar', 'to walk, to stroll');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  19, 20, 'cantar', 'to sing');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20,  1, 'comprar', 'to buy');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20,  2, 'cortar', 'to cut');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20,  3, 'desear', 'to wish, to want');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20,  4, 'entrar', 'to enter');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20,  5, 'eschuchar', 'to listen');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20,  6, 'está', 'he is, she is');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20,  7, 'explicar', 'to explain');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20,  8, 'gozar', 'to enjoy');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20,  9, 'gritar', 'to shout');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20, 10, 'invitar', 'to invite');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20, 11, 'llegar', 'to arrive');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20, 12, 'llorar', 'to cry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20, 13, 'necesitar', 'to need');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20, 14, 'practicar', 'to practice');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20, 15, 'preguntar', 'to ask');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20, 16, 'preparar', 'to prepare');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20, 17, 'soplar', 'to blow (out)');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20, 18, 'sopla las velas', 'he blows out the candles');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20, 19, 'tomar', 'to take');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  20, 20, 'va', 'he is going, she is going');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21,  1, '¡vamos!', 'let''s');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21,  2, 'contento', 'happy');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21,  3, 'delicioso', 'delicious');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21,  4, 'ese', 'that');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21,  5, 'este', 'this');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21,  6, 'feliz', 'happy');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21,  7, 'lleno', 'filled (with)');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21,  8, 'magnífico, magnifica', 'magnificent');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21,  9, 'ocupado, ocupada', 'busy');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21, 10, 'pobre', 'poor');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21, 11, 'su', 'his, her, your (formal)');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21, 12, 'típico, típica', 'typical');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21, 13, 'triste', 'sad');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21, 14, 'tu', 'your (familiar)');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21, 15, 'cuando', 'when');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21, 16, 'cuatro', 'four');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21, 17, '¿donde?', 'where?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21, 18, 'él', 'he');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21, 19, 'ella', 'she');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  21, 20, 'ellos', 'they');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22,  1, 'entonces', 'then');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22,  2, 'hoy', 'today');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22,  3, 'hoy cumple cuatro años', 'today he is four years old');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22,  4, 'más', 'more, most');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22,  5, 'que', 'who');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22,  6, '¿qué?', 'what?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22,  7, 'tú', 'you (familiar)');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22,  8, 'un, una', 'a');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22,  9, 'usted', 'you (formal)');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22, 10, 'llegar', 'to arrive');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22, 11, 'Yo llego', 'I arrive');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22, 12, 'Tú llegas', 'You arrive');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22, 13, 'Él llega', 'He arrives');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22, 14, 'Ella llega', 'She arrives');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22, 15, 'Usted llega', 'You arrive');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22, 16, 'Nosotros llegamos', 'We arrive');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22, 17, 'Vosotros llegáis', 'You arrive');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22, 18, 'Ellos llegan', 'They arrive');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22, 19, 'Ellas llegan', 'They arrive');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  22, 20, 'Ustedes llegan', 'You arrive');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23,  1, 'llevar', 'to carry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23,  2, 'Yo llevo', 'I carry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23,  3, 'Tú llevas', 'You carry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23,  4, 'Él lleva', 'He carries');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23,  5, 'Ella lleva', 'She carries');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23,  6, 'Usted lleva', 'You carry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23,  7, 'Nosotros llevamos', 'We carry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23,  8, 'Vosotros llevais', 'you carry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23,  9, 'Ellos llevan', 'They carry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23, 10, 'Ellas llevan', 'They carry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23, 11, 'Ustedes llevan', 'You carry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23, 12, 'llorar', 'to cry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23, 13, 'Yo lloro', 'I cry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23, 14, 'Tú lloras', 'You cry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23, 15, 'Él llora', 'He cries');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23, 16, 'Ella llora', 'She cries');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23, 17, 'Usted llora', 'You cry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23, 18, 'Nosotros lloramos', 'We cry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23, 19, 'Vosotros lloráis', 'You cry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  23, 20, 'Ellos lloran', 'they cry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24,  1, 'Ellas lloran', 'they cry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24,  2, 'Ustedes lloran', 'You cry');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24,  3, 'tomar', 'to take');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24,  4, 'Yo tomo', 'I take');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24,  5, 'Tú tomas', 'You take');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24,  6, 'Él toma', 'He takes');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24,  7, 'Ella toma', 'She takes');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24,  8, 'usted toma', 'You take');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24,  9, 'Nosotros tomamos', 'We take');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24, 10, 'Vosotors tomáis', 'You take');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24, 11, 'Ellos toman', 'He takes');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24, 12, 'Ellas toman', 'She takes');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24, 13, 'Ustedes toman', 'You take');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24, 14, 'buscar', 'to look for');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24, 15, 'Yo busco', 'I look for');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24, 16, 'Tú buscas', 'you look for');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24, 17, 'Él busca', 'He looks for');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24, 18, 'Ella busca', 'She looks for');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24, 19, 'Usted busca', 'You look for');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  24, 20, 'Nosotros buscamos', 'We look for');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25,  1, 'Vosotros buscáis', 'You look for');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25,  2, 'Ellos buscan', 'He looks for');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25,  3, 'Ellas buscan', 'She looks for');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25,  4, 'Ustedes buscan', 'You look for');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25,  5, 'la Calle Trienta y Cinco', 'Thirty-fifth Street');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25,  6, 'la carta', 'the letter');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25,  7, 'el fantasma', 'the ghost');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25,  8, 'el helado', 'ice cream');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25,  9, 'el horror', 'the horror');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25, 10, 'la invitación', 'the invitation');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25, 11, 'Juanita', 'Janie, Jeanie');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25, 12, 'la luz', 'the light');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25, 13, 'la máscara', 'the mask');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25, 14, 'la mesa', 'the table');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25, 15, 'el número', 'the number');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25, 16, 'la puerta', 'the door');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25, 17, 'la reunión', 'the meeting');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25, 18, 'la sorpresa', 'the surprise');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25, 19, 'el trienta y uno de octubre', 'October 31st');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  25, 20, 'la Víspera de Todos los Santos', 'Halloween');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26,  1, 'abrir', 'to open');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26,  2, 'asistir', 'to attend');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26,  3, 'beber', 'to drink');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26,  4, 'comer', 'to eat');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26,  5, 'comprender', 'to understand');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26,  6, 'correr', 'to run');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26,  7, 'dice', 'she says');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26,  8, 'escribir', 'to write');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26,  9, 'están', 'they are (with certain adjectives, and location)');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26, 10, 'leer', 'to read');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26, 11, 'no hay', 'there is no, there are no');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26, 12, 'pasar', 'to happen');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26, 13, 'recibir', 'ro receive');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26, 14, 'saber', 'to know');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26, 15, 'salier (de)', 'to leave, to go out');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26, 16, 'tocar a la puerta', 'to knock at the door');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26, 17, 'vivir', 'to live');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26, 18, 'cosas buenas', 'good things');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26, 19, 'extraño,a', 'strange');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  26, 20, 'loco,a', 'crazy');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27,  1, 'loco de curiosidad', 'crazy with curiosity');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27,  2, 'misterioso,a', 'mysterious');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27,  3, 'nervioso,a', 'nervous');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27,  4, 'otro,a', 'other');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27,  5, 'sorprendido,a', 'surprised');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27,  6, 'a las once de la noche', 'at eleven PM');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27,  7, 'claro', 'of course');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27,  8, '¿de quién?', 'from whom?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27,  9, 'en', 'on');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27, 10, 'nadie', 'nobody');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27, 11, 'noventa y nueve', 'ninety-nine');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27, 12, '¿qué?', 'what a...?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27, 13, '¿quién?', 'who?');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27, 14, 'tarde', 'late');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27, 15, 'un a', 'one');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27, 16, 'una a', 'one');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27, 17, 'aprender', 'to learn');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27, 18, 'creer', 'to believe');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27, 19, 'responder', 'to answer');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  27, 20, 'saber', 'to know');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28,  1, 'vender', 'to sell');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28,  2, 'ahora', 'now');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28,  3, 'hoy', 'today');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28,  4, 'mañana', 'tomorrow');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28,  5, 'después', 'afterwards');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28,  6, 'esta noche', 'this night (tonight)');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28,  7, 'a las once', 'at ll');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28,  8, 'a las cuatro', 'at 4');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28,  9, 'muy tarde', 'very late');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28, 10, 'abrir', 'to open');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28, 11, 'asistir', 'to attend');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28, 12, 'cubrir', 'to cover');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28, 13, 'describir', 'to describe');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28, 14, 'escribir', 'to write');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28, 15, 'omitir', 'to omit');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28, 16, 'partir', 'to leave');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  28, 17, 'recibir', 'to receive');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  29, 18, 'salir (de)', 'to leave, to go out');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  29, 19, 'subir', 'to go up, to get into');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  29, 20, 'vivir', 'to live');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  29,  1, 'los teatros', 'the theatres');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  29,  2, 'los conciertos', 'the concerts');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  29,  3, 'la clase', 'the class');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  29,  4, 'la escuela', 'the school');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  29,  5, 'la reunión', 'the meeting');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  29,  6, 'la fiesta', 'the party');
insert into bahasa.card(programid, level, seq, quest, answer) values( 2,  29,  7, 'los cines', 'the movies');
