insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96,  1, 'w', 'कमल','क,म,ल','ka-ma-la','lotus');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96,  2, 'w', 'खग','ख,ग','kha-ga','bird');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96,  3, 'w', 'गगन','ग,ग,न','ga-ga-na','sky');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96,  4, 'w', 'घटः','घ,टः','gha-ṭah','jar');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96,  5, 'w', 'चरण','च,र,ण','ca-ra-ṇa','foot');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96,  6, 'w', 'छदन','छ,द,न','cha-da-na','covering');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96,  7, 'w', 'जल','ज,ल','ca-la','water');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96,  8, 'w', 'झरः','झ,रः','jha-rah','cascade, waterfall');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96,  9, 'w', 'तपन','त,प,न','ta-pa-na','heating');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96, 10, 'w', 'दमः','द,मः','da-mah','restraint');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96, 11, 'w', 'धन','ध,न','dha-na','wealth, money');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96, 12, 'w', 'नर','न,र','na-ra','man');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96, 13, 'w', 'पठन','प,ठ,न','pa-ṭha-na','reading, studying');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96, 14, 'w', 'फल','फ,ल','pha-la','fruit');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96, 15, 'w', 'बल','ब,ल','ba-la','strength');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96, 16, 'w', 'भय','भ,य','bha-ya','fear');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96, 17, 'w', 'मम','म,म','ma-ma','my');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96, 18, 'w', 'यम','य,म','ya-ma','universal law');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96, 19, 'w', 'रथः','र,थः','ra-thah','chariot');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 96, 20, 'w', 'लयः','ल,यः','la-yah','absorption');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97,  1, 'w', 'वन','व,न','va-na','forest');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97,  2, 'w', 'शतक','श,त,क','śa-ta-ka','group of 100');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97,  3, 'w', 'शतक','श,त,क','sa-ka-la','whole, entire');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97,  4, 'w', 'हर','ह,र','ha-ra','remover');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97,  5, 'w', 'काल','का,ल','kā-la','time');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97,  6, 'w', 'जाल','जा,ल','jā-la','net');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97,  7, 'w', 'तारा','ता,रा','tā-rā','star');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97,  8, 'w', 'नारायण','ना,रा,य,ण','nā-rā-ya-ṇa','name of Vishnu');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97,  9, 'w', 'भाषा','भा,षा','bhā-ṣā','language');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97, 10, 'w', 'रामायण','रा,मा,य,ण','rā-mā-ya-ṇa','story of Rama');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97, 11, 'w', 'हासः','हा,सः','hā-sah','laughter');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97, 12, 'w', 'तिलक','ति,ल,क','ti-la-ka','vertical mark on forehead');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97, 13, 'w', 'दिवस','दि,व,स','di-va-sa','day');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97, 14, 'w', 'मिलन','मि,ल,न','mi-la-na','meeting');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97, 15, 'w', 'लिरित','लि,रि,त','li-ri-ta','stopping, cessation');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97, 16, 'w', 'लिरित','लि,रि,त','li-ri-ta','Shiva');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97, 17, 'w', 'हिमालय','हि,मा,ल,य','hi-mā-la-ya','Himalaya');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97, 18, 'w', 'हिमालय','हि,मा,ल,य','hi-mā-la-ya','song');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97, 19, 'w', 'जीव','जी,व','jī-va','individual soul');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 97, 20, 'w', 'तीर','ती,र','tī-ra','shore, bank');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98,  1, 'w', 'दीन','दी,न','dī-na','poor');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98,  2, 'w', 'दीन','दी,न','dī-na','seat');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98,  3, 'w', 'लीला','ली,ला','lī-lā','play');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98,  4, 'w', 'वीर','वी,र','vī-ra','hero');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98,  5, 'w', 'शीतल','शी,त,ल','śī-ta-la','cool');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98,  6, 'w', 'कुसुम','कु,सु,म','ku-su-ma','flower');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98,  7, 'w', 'गुरु','गु,रु','gu-ru','teacher');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98,  8, 'w', 'तुरग','तु,र,ग','tu-ra-ga','horse');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98,  9, 'w', 'पुरुष','पु,रु,ष','pu-ru-ṣa','man, self');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98, 10, 'w', 'भुज','भु,ज','bhu-ja','arm');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98, 11, 'w', 'मुख','मु,ख','mu-kha','mouth, face');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98, 12, 'w', 'शुभ','शु,भ','śu-bha','good, auspicious');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98, 13, 'w', 'सुख','सु,ख','su-kha','happiness');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98, 14, 'w', 'दूर','दू,र','dū-ra','far, distant');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98, 15, 'w', 'धूम','धू,म','dhū-ma','smoke');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98, 16, 'w', 'पूरित','पू,रि,त','pū-ri-ta','filled');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98, 17, 'w', 'भूत','भू,त','bhū-ta','being');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98, 18, 'w', 'रूप','रू,प','rū-pa','form, beauty');
insert into bahasa.card(programid, level, seq, part, quest, components, translit, answer) values(6, 98, 19, 'w', 'शूर','शू,र','śū-ra','hero');

insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99,  1, 'w', 'गृह', 'gṛ-ha', 'गृ,ह', 2, 'home');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99,  2, 'w', 'तृण', 'tṛ-ṇa', 'तृ,ण', 2, 'grass');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99,  3, 'w', 'नृपति', 'nṛ-pa-ti', 'नृ,प,ति', 3, 'king');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99,  4, 'w', 'हदय', 'ha-da-ya', 'ह,द,य', 3, 'heart');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99,  5, 'w', 'तॄ', 'tṝ', 'तॄ', 1, 'to cross');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99,  6, 'w', 'पॄ', 'pṝ', 'पॄ', 1, 'to fill');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99,  7, 'w', 'जेतृ', 'je-tṛ', 'जे,तृ', 2, 'conqueror');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99,  8, 'w', 'देव', 'de-va', 'दे,व', 2, 'god');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99,  9, 'w', 'सेवा', 'se-vā', 'से,वा', 2, 'service');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99, 10, 'w', 'हेम', 'he-ma', 'हे,म', 2, 'gold');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99, 11, 'w', 'कैलास', 'kai-lā-sa', 'कै,ला,स', 3, 'mountain');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99, 12, 'w', 'जैन', 'jai-na', 'जै,न', 2, 'name of religion');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99, 13, 'w', 'तैजस', 'tai-ja-sa', 'तै,ज,स', 3, 'brilliance');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99, 14, 'w', 'भरव', 'bha-ra-va', 'भ,र,व', 3, 'name of Shiva');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99, 15, 'w', 'सेवा', 'se-vā', 'से,वा', 2, 'soft');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99, 16, 'w', 'गोपाल', 'go-pā-la', 'गो,पा,ल', 3, 'name of Krishna');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99, 17, 'w', 'दोब', 'do-ba', 'दो,ब', 2, 'defect');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99, 18, 'w', 'मोजन', 'mo-ja-na', 'मो,ज,न', 3, 'eating, meal');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99, 19, 'w', 'गौतम', 'gau-ta-ma', 'गौ,त,म', 3, 'name of Buddha');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6,  99, 20, 'w', 'धौत', 'dhau-ta', 'धौ,त', 2, 'purified');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6, 100,  1, 'w', 'नौ', 'nau', 'नौ', 1, 'boat, both of us');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6, 100,  2, 'w', 'यौवन', 'yau-va-na', 'यौ,व,न', 3, 'youth');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6, 100,  3, 'w', 'अतिथि', 'a-ti-thi', 'अ,ति,थि', 3, 'guest');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6, 100,  4, 'w', 'आकाश', 'ā-kā-śa', 'आ,का,श', 3, 'space');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6, 100,  5, 'w', 'इतर', 'i-ta-ra', 'इ,त,र', 3, 'other');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6, 100,  6, 'w', 'ईश', 'ī-śa', 'ई,श', 2, 'lord');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6, 100,  7, 'w', 'उदार', 'u-dā-ra', 'उ,दा,र', 3, 'generous');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6, 100,  8, 'w', 'ऊरू', 'ū-rū', 'ऊ,रू', 2, 'thigh');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6, 100,  9, 'w', 'ऋषि', 'ṛ-ṣi', 'ऋ,षि', 2, 'sage');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6, 100, 10, 'w', 'एकदा', 'e-ka-dā', 'ए,क,दा', 3, 'once upon a');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6, 100, 11, 'w', 'ऐरावत', 'ai-rā-va-ta', 'ऐ,रा,व,त', 4, 'elephant (Indra''s vehicle');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6, 100, 12, 'w', 'ओदन', 'o-da-na', 'ओ,द,न', 3, 'cooked rice');
insert into bahasa.card(programid, level, seq, part, quest, translit, components, numcomponents, answer) values (6, 100, 13, 'w', 'औषधि', 'au-ṣa-dhi', 'औ,ष,धि', 3, 'herb, medicine');

insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101,  1, 'योग', 'yoga');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101,  2, 'हठयोग', 'hatha yoga');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101,  3, 'कुण्डलिनी', 'kundalini');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101,  4, 'प्राण', 'prana');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101,  5, 'प्राणायाम', 'pranayama');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101,  6, 'आसन', 'asana');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101,  7, 'विन्यास', 'vinyasa');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101,  8, 'चक्रं', 'chakra');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101,  9, 'नमस्ते', 'namaste');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101, 10, 'ॐ', 'om');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101, 11, ' ', 'ujjayi');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101, 12, ' ', 'yogi');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101, 13, 'योगिनी', 'yogini');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101, 14, 'आश्रम', 'ashram');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101, 15, 'गुरु', 'guru');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101, 16, 'मुद्रा', 'mudra');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101, 17, 'मन्त्र', 'mantra');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101, 18, 'यन्त्रं', 'yantra');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101, 19, 'सूत्र', 'sutra');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 101, 20, 'मण्डल', 'mandala');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102,  1, ' ', 'kirtan');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102,  2, 'देवनागरी', 'devanagari');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102,  3, 'संस्कृतम्', 'sanskrit');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102,  4, 'शिव', 'shiva');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102,  5, 'शक्ती', 'shakti');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102,  6, 'तन्त्र', 'tantra');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102,  7, 'आकाश', 'akasha');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102,  8, '', 'nadi');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102,  9, 'मेत्ता', 'metta / maitri');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102, 10, '', 'jedi');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102, 11, 'कुल', 'kula');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102, 12, '', 'shala');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102, 13, 'संघ', 'sangha');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102, 14, '', 'satsang');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102, 15, 'धर्म', 'dharma');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102, 16, 'कर्म', 'karma');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102, 17, '', 'drishti');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102, 18, 'समाधि', 'samadhi');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102, 19, '', 'kaivalya');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 102, 20, 'मोक्ष', 'moksha');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 103,  1, 'मुक्ति', 'mukti');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 103,  2, 'आयुर्वेद', 'ayurveda');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 103,  3, 'भगवद्गीता', 'Bhagavad Gita');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 103,  4, 'पतञ्जलि', 'Patanjali');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 103,  5, 'सहस्रार', 'Sahasrara');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 103,  6, 'आज्ञा', 'Ajna');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 103,  7, 'विशुद्ध', 'Vishuddha');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 103,  8, 'अनाहत', 'Anahata');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 103,  9, 'मणिपूर', 'Manipura');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 103, 10, 'स्वाधिष्ठान', 'Swadhistana');
insert into bahasa.card(programid, level, seq, quest, answer) values (6, 103, 11, 'मूलाधार', 'Muladhara');
